version: '3'

services:
  auth-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${APP_PORT:-8080}:8080"
    environment:
      - DB_HOST=${DB_HOST:-db}
      - DB_PORT=${DB_PORT:-5432}
      - DB_USER=${DB_USER:-postgres}
      - DB_PASSWORD=${DB_PASS:-postgres}
      - DB_NAME=${DB_NAME:-authdb}
      - JWT_SECRET=${JWT_SECRET:-defaultsecretkey}
      - JWT_TOKEN_LIFESPAN=${JWT_TOKEN_LIFESPAN:-3600}
      - PWD=${PWD:-/app}
    depends_on:
      - db
    restart: unless-stopped

  db: 
    image: postgres:14
    environment:
      - POSTGRES_USER=${DB_USER:-postgres}
      - POSTGRES_PASSWORD=${DB_PASS:-postgres}
      - POSTGRES_DB=${DB_NAME:-authdb}
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/db